### ISSUE TITLE
Pinterest Plus Premium Bug on Pinterest

### ISSUE THREAD

**Issue by Pott20** [Iquaridys/Snurf-Corp#3]
hi,

when I am using the sorting function of pinterest Plus premium and it finished the work, the site is completly blank. the pins are gone.

what I can do?

cheers

**Comment by Iquaridys** [comment]
hi pott20, 

how many pages are you sorting?

sometimes if there are too many pages, the browser is not strong enough to store the results of sorting.

this requires more research because this is caused by the browser not from the extension

**Comment by Iquaridys** [comment]
hi  @Pott20  

how many pages are you sorting?

sometimes if there are too many pages, the browser is not strong enough to store the results of sorting.

this requires more research because this is caused by the browser not from the extension

best way you need to reduce it, and repeat sort with another relevant by your keyword.

i think if you need loots page best way is 15, or 20 without with high tab work to avoid errors,
15 pages is like 500++ pin's / images

**Comment by Pott20** [comment]
Hi,

thx for your reply. I tried different amounts of sites, even only one
site. I have the default configuration of chrome. Should I change there
something?

Cheers
Pott

Am 05.04.2019 um 23:12 schrieb Olivia:

**Comment by Iquaridys** [comment]
@Pott20 


hi thank you for the response,

may i know what you mean by site?

to do sorting you need to pinterest, based on timeline, profile or keyword and you need to enter how many pages to be sorted, for 20 pages I think maybe about 600 more images.

sometimes when more pages are stuck, I'm still trying to fix this problem.

**Comment by Pott20** [comment]
Hi,

sry I mean pages not sides.
I cannot even sort one pinterest page (with a specific) keyword.

Cheers

Am 07.04.2019 um 16:02 schrieb Olivia:

**Comment by Iquaridys** [comment]
@Pott20 

I will ask,
is your url address pinterest.com or use local area like nz.pinterest.com or id.pinterest.com?
if you use Pinterest as local as I explained earlier, and you use chrome this error occurs.

I temporarily advised to replace it to pinterest.com, this how to change it:
Edit Settings -> Account Settings and change the Country to United States, after change u need just reload or go to pinterest.com.

that happens if you use chrome, if you use the vivaldi browser you don't need to do it.

if this method does not solve the problem, can you explain in more detail and include photos

thank you

**Comment by Iquaridys** [comment]
@Pott20 
and can u give URL the image of Skinny Chicken, if forget can i know the profile / board you see that PIN

thanks
