### ISSUE TITLE
Stopped working correctly

### ISSUE THREAD

**Issue by horsecarrot** [Iquaridys/Snurf-Corp#4]
Hey, the plugin seems to have stopped working correctly, isn't showing repins on pins just the total saves and repins displayed as 0.

**Comment by Iquaridys** [comment]
I have never had an error like that

if later you find it again
You can capture and give the keywords you are looking for in the sorting.

thank you

**Comment by Iquaridys** [comment]
I have never had an error like that

if later you find it again
You can capture and give the keywords you are looking for in the sorting.

thank you @horsecarrot

**Comment by Iquaridys** [comment]
I have never made such an error

if later you find it again, please take a picture and give the keyword you are looking for in sorting.

thank you @horsecarrot

**Comment by Iquaridys** [comment]
I have never experienced such an error

if later you find it again, please take a picture and give the keyword you are looking for in sorting.

thank you @horsecarrot

**Comment by horsecarrot** [comment]
Hello,

I'm not sure if this problem is just on my end but I'll try to explain with a screenshot.

https://i.imgur.com/tcjwP2Q.jpg

As you can see here, each pin has 'Repin: 0'. Sometimes it will show as 'Repin: -1'.

It used to be the case that each pin would show the exact number of repins that individual pin itself had got, alongside the total save count which still displays correctly.

This is how it used to display for me: https://i.imgur.com/3U9VBun.jpg

The change happened around 6 days ago, so I'm not sure if it's a problem on my end or if others are experiencing this too.

Could you please check for me and get back?

Love your work,
Thanks!

**Comment by Iquaridys** [comment]
@horsecarrot,

thank you for the information you have given,

I did not change the code on the repin, or maybe this happened when I changed something that had an impact on repin.

For info that appears on each PIN provided on API Pinterest: [Pinterest API](https://developers.pinterest.com/docs/api/pins/), 
all data that appears is the data provided by Pinterest itself. Maybe this happened because of my code wrong or this is indeed the data given from pinterest.

I will still make improvements to this problem.
Thank you, for reporting, I hope I can quickly resolve this matter

**Comment by Iquaridys** [comment]
@horsecarrot , and can u give URL the image of Skinny Chicken, if forget can i know the profile / board you see that PIN

thanks

**Comment by Iquaridys** [comment]
![Capture](https://user-images.githubusercontent.com/23011078/55685705-906a8a80-5983-11e9-923b-6da1c0aab363.PNG)

Seen in the picture above, the data provided is data from Pinterest.

This proves there is no code error in the app.

and for the change of repin, I think it's impossible if it's exchanged between the first pin and the other one.

why am I sure the code is not wrong, if the Repin data changes should the number of digits in the Saves should also be exchanged, because the data displayed between Save, Repins Like, and Day, is one unit / one data.

May Pinterest did an update, which resulted in some images / pins having error as seen or I don't know what happened

@horsecarrot
