### ISSUE TITLE
Pinterest Plus Premium Bug

### ISSUE THREAD

**Issue by horsecarrot** [Iquaridys/Snurf-Corp#5]
Hi,

This extension is no longer working for the account that you're logged into on Pinterest. It still works on other accounts, but if you view your own pins it doesn't load at all.

Is there any way to fix this? I use it to delete pins that aren't performing so need to see my own pins stats.

Thanks,
Michael.

**Comment by Iquaridys** [comment]
hi sir Michael, 
i try to my another account and still work 

you can see my profile and my pin, this stats show up

![image](https://user-images.githubusercontent.com/23011078/60225308-72406680-98b0-11e9-808b-1540ab8c73b4.png)

Pinterest requires having a good connection, because it has a lot of pictures. try to close your browser tab and reopen, make sure your internet connection is in the best performance
